# Change these first
owner: Bara # Your GitHub organization or username, where this repository lives
repo: StatusSite # The name of this repository
assignees:
  - Bara

sites:
  - name: Bara
    url: https://bara.dev
  - name: CSGOTTT
    url: https://csgottt.com
  - name: fuckTimer
    url: https://fucktimer.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bara.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Site | Bara
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Bara
      href: https://bara.dev
    - title: CSGOTTT
      href: https://csgottt.com
    - title: CSGOTTT - Docs
      href: https://docs.csgottt.com
    - title: fuckTimer
      href: https://fucktimer.com
      expectedStatusCodes: 
        - 500
    - title: fuckTimer - Docs
      href: https://docs.fucktimer.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
